---

- src: https://github.com/turingbeing/ansible-role-dotfiles
  version: master
  name: turingbeing.dotfiles

- src: https://github.com/turingbeing/ansible-role-homebrew
  version: master
  name: turingbeing.homebrew

- src: https://github.com/turingbeing/ansible-role-mas
  version: master
  name: turingbeing.mas
